insert into producto (id, descripcion, stockactual, stockminimo, precio) values (1, 'Stereotactic Gamma Beam Radiosurgery', 60, 4, '824.28');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (2, 'Stereotactic Gamma Beam Radiosurgery', 30, 84, '255.77');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (3, 'Stereotactic Gamma Beam Radiosurgery', 43, 21, '363.24');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (4, 'Stereotactic Gamma Beam Radiosurgery', 48, 52, '600.41');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (5, 'Stereotactic Gamma Beam Radiosurgery', 96, 21, '445.39');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (6, 'Fragmentation in Pericardium', 75, 9, '462.93');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (7, 'Fragmentation in Pericardium', 77, 79, '240.92');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (8, 'Fragmentation in Pericardium', 15, 43, '579.92');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (9, 'Fragmentation in Pericardium', 47, 94, '745.21');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (10, 'Fragmentation in Pericardium', 10, 30, '840.41');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (11, 'Fragmentation in Pericardium', 43, 47, '230.81');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (12, 'Drainage of L Shoulder', 35, 39, '273.15');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (13, 'Drainage of L Shoulder', 79, 76, '90.81');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (14, 'Drainage of L Shoulder', 28, 63, '978.27');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (15, 'Drainage of L Shoulder', 91, 83, '820.95');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (16, 'Drainage of L Shoulder', 39, 49, '934.94');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (17, 'Supplement Right Femoral Shaft', 74, 86, '398.08');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (18, 'Supplement Right Femoral Shaft', 93, 1, '135.23');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (19, 'Supplement Right Femoral Shaft', 58, 52, '339.65');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (20, 'Supplement Right Femoral Shaft', 40, 9, '965.49');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (21, 'Supplement Right Femoral Shaft', 16, 77, '80.98');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (22, 'Supplement Right Femoral Shaft', 84, 51, '741.32');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (23, 'Supplement Right Femoral Shaft', 24, 51, '715.50');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (24, 'Hyperthermia of Abdomen', 50, 8, '794.55');
insert into producto (id, descripcion, stockactual, stockminimo, precio) values (25, 'Hyperthermia of Abdomen', 36, 32, '928.45');
