insert into DEPARTAMENTO (id_dep, nombre, localidad) values (1, 'Accounting', 'California');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (2, 'Accounting', 'Illinois');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (3, 'Training', 'North Carolina');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (4, 'Accounting', 'California');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (5, 'Legal', 'Ohio');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (6, 'Training', 'Virginia');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (7, 'Marketing', 'Illinois');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (8, 'Support', 'Tennessee');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (9, 'Accounting', 'North Carolina');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (10, 'Support', 'Florida');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (11, 'Engineering', 'Michigan');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (12, 'Accounting', 'North Carolina');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (13, 'Support', 'Colorado');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (14, 'Support', 'Indiana');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (15, 'Marketing', 'Alaska');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (16, 'Engineering', 'Texas');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (17, 'Marketing', 'Alabama');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (18, 'Marketing', 'Mississippi');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (19, 'Marketing', 'New Mexico');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (20, 'Legal', 'North Carolina');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (21, 'Training', 'Virginia');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (22, 'Training', 'Tennessee');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (23, 'Legal', 'Montana');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (24, 'Training', 'Texas');
insert into DEPARTAMENTO (id_dep, nombre, localidad) values (25, 'Training', 'New York');
